# Comment to be posted on PRs from first-time contributors in Novu repository
newPRWelcomeComment: |
  Thank you for opening this pull request! ğŸ™Œ
  These tips will help get your PR across the finish line:
  - Please make sure that your PR has a descriptive title and description.
  - If this is your first time contributing to Novu, please take a look at our [Contributing Guidelines](/CONTRIBUTING.md).

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: >
  Congrats on merging your first pull request! ğŸ‰
  We here at Novu are proud of you! ğŸ˜Š

# Comment to be posted on first-time issues
newIssueWelcomeComment: >
  Thank you for opening your first issue here! ğŸ› 
  Be sure to follow the issue template!   
