apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (HEAD)
  labels:
    app.novu.co/name: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app.novu.co/name: web
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (HEAD)
      labels:
        app.novu.co/name: web
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: novu-env
          image: ghcr.io/novuhq/novu/web:0.9.0
          name: web
          ports:
            - containerPort: 4200
