name: Deploy Service

on:
  workflow_call:
    inputs:
      env:
        description: 'Deployment environment - choose between dev and prod'
        required: true
        type: string
      service:
        description: 'Service name'
        required: true
        type: string
      package_name:
        description: 'Docker package name'
        required: true
        type: string
      project_path:
        description: 'Path to the project directory'
        required: true
        type: string
      test_port:
        description: 'Service port for testing'
        required: true
        type: string
      local_tag:
        description: 'Local Docker image tag'
        required: true
        type: string

jobs:
  set_environment:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.set_env.outputs.environment }}
    steps:
      - uses: actions/checkout@v4

      - id: set_env
        run: |
          if echo "${{ inputs.env }}" | grep -qwi 'prod'; then
            echo "::set-output name=environment::Production"
          else
            echo "::set-output name=environment::Development"
          fi

  build_image:
    needs: set_environment
    secrets: inherit
    uses: ./.github/workflows/cloud-deploy-reusable-docker.yml
    with:
      environment: ${{ needs.set_environment.outputs.environment }}
      package_name: ${{ inputs.package_name }}
      project_path: ${{ inputs.project_path }}
      test_port: ${{ inputs.test_port }}
      health_check: true
      local_tag: ${{ inputs.local_tag }}
      env_tag: ${{ inputs.env }}
      enterprise: true
      submodule_token: ${{ secrets.SUBMODULES_TOKEN }}

  deploy_dev_service:
    needs:
      - build_image
      - set_environment
    uses: ./.github/workflows/cloud-deploy-reusable-app-service-deploy.yml
    if: ${{ contains(inputs.env, 'dev') }}
    secrets: inherit
    with:
      environment: ${{ needs.set_environment.outputs.environment }}
      service_name: ${{ inputs.service }}
      terraform_workspace: novu-dev
      docker_image: ghcr.io/novuhq/novu/${{ inputs.local_tag }}-ee:${{ github.sha }}

  deploy_prod_service_eu:
    needs:
      - build_image
      - set_environment
    uses: ./.github/workflows/cloud-deploy-reusable-app-service-deploy.yml
    if: ${{ !contains(inputs.env, 'dev') }}
    secrets: inherit
    with:
      environment: ${{ needs.set_environment.outputs.environment }}
      service_name: ${{ inputs.service }}
      terraform_workspace: novu-prod-eu
      docker_image: ghcr.io/novuhq/novu/${{ inputs.local_tag }}-ee:${{ github.sha }}

  deploy_prod_service_us:
    needs:
      - build_image
      - set_environment
    uses: ./.github/workflows/cloud-deploy-reusable-app-service-deploy.yml
    if: ${{ !contains(inputs.env, 'dev') }}
    secrets: inherit
    with:
      environment: ${{ needs.set_environment.outputs.environment }}
      service_name: ${{ inputs.service }}
      terraform_workspace: novu-prod
      docker_image: ghcr.io/novuhq/novu/${{ inputs.local_tag }}-ee:${{ github.sha }}
      deploy_sentry_release: true
      sentry_project: ${{ inputs.service }}
