name: Deploy Service Job

# Controls when the action will run. Triggers the workflow on push or pull request
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      service_name:
        required: true
        type: string
      docker_image:
        required: true
        type: string
      sentry_project:
        required: false
        type: string
      New_Relic_GUID:
        required: false
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  infrastructure_data:
    runs-on: ubuntu-latest
    timeout-minutes: 80
    environment: ${{ inputs.environment }}
    permissions:
      contents: read
      deployments: write
    env:
      TF_WORKSPACE: ${{ vars.TF_WORKSPACE }}
    outputs:
      ecs_container_name: ${{ steps.terraform.outputs.ecs_container_name }}
      ecs_service: ${{ steps.terraform.outputs.ecs_service }}
      ecs_cluster: ${{ steps.terraform.outputs.ecs_cluster }}
      task_name: ${{ steps.terraform.outputs.task_name }}
      aws_region: ${{ steps.terraform.outputs.aws_region }}
      services_to_deploy: ${{ steps.terraform.outputs.queue_workers_services }}
    steps:
      - run: echo "Deploying ${{ inputs.service_name }} to ${{ vars.TF_WORKSPACE }} And Docker Tag ${{ inputs.docker_image }}"

      - name: Checkout cloud infra
        uses: actions/checkout@v4
        with:
          repository: novuhq/cloud-infra
          token: ${{ secrets.GH_PACKAGES }}
          path: cloud-infra

      - name: Terraform setup
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          terraform_version: 1.5.5
          terraform_wrapper: false

      - name: Terraform Init
        working-directory: cloud-infra/terraform/novu/aws
        run: terraform init

      - name: Replace dash with underscore in service_name
        id: replace_dash
        run: echo "service_name_under=$(echo '${{ inputs.service_name }}' | tr '-' '_')" >> $GITHUB_ENV

      - name: Terraform get output
        working-directory: cloud-infra/terraform/novu/aws
        id: terraform
        env:
          SERVICE_NAME: ${{ env.service_name_under }}
        run: |
          echo "ecs_container_name=$(terraform output -json ${{ env.SERVICE_NAME }}_ecs_container_name | jq -r .)" >> $GITHUB_OUTPUT
          echo "ecs_service=$(terraform output -json ${{ env.SERVICE_NAME }}_ecs_service | jq -r .)" >> $GITHUB_OUTPUT
          echo "ecs_cluster=$(terraform output -json ${{ env.SERVICE_NAME }}_ecs_cluster | jq -r .)" >> $GITHUB_OUTPUT
          echo "task_name=$(terraform output -json ${{ env.SERVICE_NAME }}_task_name | jq -r .)" >> $GITHUB_OUTPUT
          echo "aws_region=$(terraform output -json aws_region | jq -r .)" >> $GITHUB_OUTPUT
          echo "queue_workers_services=$(terraform output -json queue_workers_services)" >> $GITHUB_OUTPUT

  deploy_service:
    needs: infrastructure_data
    runs-on: ubuntu-latest
    timeout-minutes: 80
    environment: ${{ inputs.environment }}
    permissions:
      contents: read
      deployments: write

    strategy:
      matrix:
        include:
          - service_type: worker
            matrix_config: true
            services: ${{ fromJson(needs.infrastructure_data.outputs.services_to_deploy) }}
          - service_type: other
            matrix_config: false
            services:
              - name: ${{ inputs.service_name }}
                task_name: ${{ needs.infrastructure_data.outputs.task_name }}
                container_name: ${{ needs.infrastructure_data.outputs.ecs_container_name }}
                service: ${{ needs.infrastructure_data.outputs.ecs_service }}

    steps:
      - run: echo "Deploying ${{ inputs.service_name }} to ${{ vars.TF_WORKSPACE }} with Docker tag ${{ inputs.docker_image }}"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ needs.infrastructure_data.outputs.aws_region }}

      - name: Set Service Details
        if: matrix.matrix_config
        run: |
          echo "Setting service details for worker services"
          echo "TASK_NAME=${{ matrix.services.task_name }}" >> $GITHUB_ENV
          echo "CONTAINER_NAME=${{ matrix.services.container_name }}" >> $GITHUB_ENV
          echo "SERVICE=${{ matrix.services.service }}" >> $GITHUB_ENV

      - name: Set Service Details for Non-Worker
        if: ${{ !matrix.matrix_config }}
        run: |
          echo "Setting service details for non-worker service"
          echo "TASK_NAME=${{ matrix.services[0].task_name }}" >> $GITHUB_ENV
          echo "CONTAINER_NAME=${{ matrix.services[0].container_name }}" >> $GITHUB_ENV
          echo "SERVICE=${{ matrix.services[0].service }}" >> $GITHUB_ENV

      - name: Download task definition
        run: |
          aws ecs describe-task-definition --task-definition $TASK_NAME \
          --query taskDefinition > task-definition.json

      - name: Render Amazon ECS task definition
        id: render-web-container
        uses: aws-actions/amazon-ecs-render-task-definition@39c13cf530718ffeb524ec8ee0c15882bcb13842
        with:
          task-definition: task-definition.json
          container-name: $CONTAINER_NAME
          image: ${{ inputs.docker_image }}

      - name: Deploy to Amazon ECS service
        uses: aws-actions/amazon-ecs-deploy-task-definition@3e7310352de91b71a906e60c22af629577546002
        with:
          task-definition: ${{ steps.render-web-container.outputs.task-definition }}
          service: $SERVICE
          cluster: ${{ needs.infrastructure_data.outputs.ecs_cluster }}
          wait-for-service-stability: true

  post-deploy:
    needs:
      - infrastructure_data
      - deploy_service
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: read
    steps:
      - uses: actions/checkout@v4

      - name: get-npm-version
        if: ${{ vars.DEPLOY_SENTRY_RELEASE }}
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main
        with:
          path: apps/${{ inputs.sentry_project }}

      - name: Create Sentry release
        if: ${{ vars.DEPLOY_SENTRY_RELEASE }}
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: novu-r9
          SENTRY_PROJECT: ${{ inputs.sentry_project }}
        with:
          version: ${{ steps.package-version.outputs.current-version}}
          version_prefix: v
          environment: prod
          ignore_empty: true
          ignore_missing: true

      - name: Set New Relic Region
        if: ${{ inputs.New_Relic_GUID }}
        id: set_region
        run: |
          if [[ "${{ env.aws_region }}" == *"us"* ]]; then
            echo "New_Relic_Region=US" >> ${GITHUB_ENV}
          else
            echo "New_Relic_Region=EU" >> ${GITHUB_ENV}
          fi
        shell: bash

      - name: New Relic Application Deployment Marker
        if: ${{ inputs.New_Relic_GUID }}
        uses: newrelic/deployment-marker-action@v2.3.0
        with:
          region: ${{ env.New_Relic_Region }}
          apiKey: ${{ secrets.NEW_RELIC_API_KEY }}
          guid: ${{ inputs.New_Relic_GUID }}
          version: "v${{ steps.package-version.outputs.current-version }}"
          user: "${{ github.actor }}"

