name: Deploy PROD WS

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:

jobs:
  test_ws:
    strategy:
      matrix:
        name: [ 'novu/ws-ee', 'novu/ws' ]
    uses: ./.github/workflows/reusable-ws-e2e.yml
    with:
      ee: ${{ contains (matrix.name,'ee') }}
      submodules: ${{ contains (matrix.name,'ee') }}
      submodule_branch: 'main'
    secrets: inherit

  # This workflow contains a single job called "build"
  build_prod_image:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 80
    environment: Production
    needs:
      - test_ws
    strategy:
      matrix:
        name: [ 'novu/ws-ee', 'novu/ws' ]
    outputs:
      docker_image: ${{ steps.build-image.outputs.IMAGE }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-project

      - name: Set Bull MQ Env variable for EE
        if: contains(matrix.name, 'ee')
        shell: bash
        run: |
          echo "BULL_MQ_PRO_NPM_TOKEN=${{ secrets.BULL_MQ_PRO_NPM_TOKEN }}" >> $GITHUB_ENV

      - name: build api
        run: pnpm build:ws

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          REGISTRY_OWNER: novuhq
          DOCKER_NAME: ${{matrix.name}}
          IMAGE_TAG: ${{ github.sha }}
          GH_ACTOR: ${{ github.actor }}
          GH_PASSWORD: ${{ secrets.GH_PACKAGES }}
        run: |
          echo $GH_PASSWORD | docker login ghcr.io -u $GH_ACTOR --password-stdin 
          docker build --build-arg BULL_MQ_PRO_TOKEN=${BULL_MQ_PRO_NPM_TOKEN} -t ghcr.io/$REGISTRY_OWNER/$DOCKER_NAME:$IMAGE_TAG -f apps/ws/Dockerfile .
          docker run --network=host --name api -dit --env NODE_ENV=test ghcr.io/$REGISTRY_OWNER/$DOCKER_NAME:$IMAGE_TAG
          docker run --network=host appropriate/curl --retry 10 --retry-delay 5 --retry-connrefused http://localhost:1340/v1/health-check | grep 'ok'
          docker tag ghcr.io/$REGISTRY_OWNER/$DOCKER_NAME:$IMAGE_TAG ghcr.io/$REGISTRY_OWNER/$DOCKER_NAME:prod
          docker tag ghcr.io/$REGISTRY_OWNER/$DOCKER_NAME:$IMAGE_TAG ghcr.io/$REGISTRY_OWNER/$DOCKER_NAME:latest
          docker push ghcr.io/$REGISTRY_OWNER/$DOCKER_NAME:prod
          docker push ghcr.io/$REGISTRY_OWNER/$DOCKER_NAME:latest
          docker push ghcr.io/$REGISTRY_OWNER/$DOCKER_NAME:$IMAGE_TAG
          echo "IMAGE=ghcr.io/$REGISTRY_OWNER/$DOCKER_NAME:$IMAGE_TAG" >> $GITHUB_OUTPUT

  deploy_prod_ws_eu:
    needs:
      - build_prod_image
    uses: ./.github/workflows/reusable-app-service-deploy.yml
    secrets: inherit
    with:
      environment: Production
      service_name: ws
      terraform_workspace: novu-prod-eu
      # This is a workaround to an issue with matrix outputs
      docker_image: ghcr.io/novuhq/novu/ws-ee:${{ github.sha }}
      deploy_sentry_release: true
      sentry_project: ws

  deploy_prod_ws_us:
    needs:
      - deploy_prod_ws_eu
      - build_prod_image
    uses: ./.github/workflows/reusable-app-service-deploy.yml
    secrets: inherit
    with:
      environment: Production
      service_name: ws
      terraform_workspace: novu-prod
      # This is a workaround to an issue with matrix outputs
      docker_image: ghcr.io/novuhq/novu/ws-ee:${{ github.sha }}
      deploy_sentry_release: true
      sentry_project: ws
