# This is a basic workflow to help you get started with Actions

name: Deploy PROD WEB

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test_web:
    uses: ./.github/workflows/reusable-web-e2e.yml
    with:
      ee: true
    secrets: inherit

  deploy_web_eu:
    needs: test_web
    uses: ./.github/workflows/reusable-web-deploy.yml
    with:
      environment: Production
      react_app_api_url: https://eu.api.novu.co
      react_app_ws_url: https://eu.ws.novu.co
      react_app_webhook_url: https://eu.webhook.novu.co
      react_app_widget_embed_path: https://eu.embed.novu.co/embed.umd.min.js
      react_app_sentry_dsn: https://2b5160da86384949be4cc66679c54e79@o1161119.ingest.sentry.io/6250907
      react_app_environment: production
      react_app_mail_server_domain: eu.inbound-mail.novu.co
      react_app_hubspot_embed: 44416662
      netlify_deploy_message: Prod deployment
      netlify_alias: prod
      netlify_gh_env: Production
      netlify_site_id: d2e8b860-7016-4202-9256-ebca0f13259a
    secrets: inherit

  deploy_web_us:
    needs:
      - test_web
      - deploy_web_eu
    uses: ./.github/workflows/reusable-web-deploy.yml
    with:
      environment: Production
      react_app_api_url: https://api.novu.co
      react_app_ws_url: https://ws.novu.co
      react_app_webhook_url: https://webhook.novu.co
      react_app_widget_embed_path: https://embed.novu.co/embed.umd.min.js
      react_app_sentry_dsn: https://2b5160da86384949be4cc66679c54e79@o1161119.ingest.sentry.io/6250907
      react_app_environment: production
      react_app_mail_server_domain: inbound-mail.novu.co
      react_app_hubspot_embed: 44416662
      netlify_deploy_message: Prod deployment
      netlify_alias: prod
      netlify_gh_env: Production
      netlify_site_id: 8639d8b9-81f9-44c3-b885-585a7fd2b5ff
    secrets: inherit

  deploy_docker:
    needs:
      - deploy_web_us
      - deploy_web_eu
    uses: ./.github/workflows/reusable-docker.yml
    with:
      environment: Production
      package_name: novu/web
      project_path: apps/web
      local_tag: novu-web
      env_tag: prod
    secrets: inherit
