name: Scheduled E2E tests

on:
  workflow_dispatch:
  schedule:
   - cron:  '0 7-19/4 * * 1-5'
permissions:
  contents: read
  packages: write
  deployments: write
  id-token: write
  actions: write

env:
  OWNER: ${{ github.repository_owner }}
  REPO: ${{ github.event.repository.name }}
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test_web:
    name: Test Web Cypress
    uses: ./.github/workflows/reusable-web-e2e.yml
    secrets: inherit
    environment: Development
    with:
      ee: true
      slack_notification: true

  test_widget:
    name: Test Widget Cypress
    uses: ./.github/workflows/reusable-widget-e2e.yml
    environment: Development
    with:
      ee: true
      slack_notification: true
    secrets: inherit

  release_decision:
    name: Release Decision
    if: always()
    runs-on: ubuntu-latest
    needs:
      - test_widget
      - test_web
    steps:
      - uses: actions/checkout@v4
      - name: Check and manage workflows
        run: |
          needs_json='${{ toJSON(needs) }}'
          web_status=$(echo "$needs_json" | jq -r '.test_web.result')
          widget_status=$(echo "$needs_json" | jq -r '.test_widget.result')
          workflows_map=$(cat << EOF
          prod-deploy-widget.yml: $widget_status
          prod-deploy-web.yml: $web_status
          EOF
          )
          while IFS= read -r line; do
            filename=$(echo "$line" | awk -F ':' '{print $1}')
            status=$(echo "$line" | awk -F ':' '{print $2}' | awk '{$1=$1};1') # Trim whitespace
            echo "Workflow $filename status: $status"

            if [[ "$status" == "failure" ]]; then
              echo "Disabling workflow $filename. The E2E test has failed."
              gh workflow disable "$filename"
            elif [[ "$status" == "success" ]]; then
              echo "Enabling workflow $filename. The E2E tests have passed."
              gh workflow enable "$filename"
            else
              echo "Unknown status for workflow $filename: $status"
            fi
          done <<< "$workflows_map"
