# This is a basic workflow to help you get started with Actions

name: Test API

# Controls when the action will run. Triggers the workflow on push or pull request
on:
  pull_request:
    paths:
      - 'package.json'
      - 'yarn.lock'
      - 'apps/api/**'
      - 'libs/dal/**'
      - 'libs/testing/**'
      - 'libs/shared/**'
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test_api:
    uses: ./.github/workflows/reusable-api-e2e.yml

  build_docker:
    runs-on: ubuntu-latest
    timeout-minutes: 80
    permissions:
      contents: read
      packages: write
      deployments: write
      id-token: write
    strategy:
      matrix:
        name: ['novu/api', 'novu/api-ee']
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-project
      - uses: ./.github/actions/setup-redis-cluster
      - uses: ./.github/actions/docker/build-api
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fork: ${{ github.event.pull_request.head.repo.fork }}
          docker_name: ${{ matrix.name }}
