- name: Build API
run: CI='' pnpm build:api# This is a basic workflow to help you get started with Actions

name: Test WIDGET

# Controls when the action will run. Triggers the workflow on push or pull request
on:
  workflow_dispatch:
    inputs:
      deploy:
        description: 'Should deploy'
        required: false
        default: "true"
  pull_request:
    paths:
      - 'apps/widget/**'
      - 'apps/ws/**'
      - 'libs/shared/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test_widget:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 80

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup kernel for react native, increase watchers
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
      - uses: actions/setup-node@v2
        with:
          node-version: '16.13.0'
      - name: Start Redis
        uses: supercharge/redis-github-action@1.2.0

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: 4.2.8

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.0.2
          run_install: true

      - uses: mansagroup/nrwl-nx-action@v2
        with:
          targets: lint
          projects: "@notifire/widget"

      # Runs a single command using the runners shell
      - name: Build
        run: CI='' pnpm build:widget

      - name: Build API
        run: CI='' pnpm build:api

      # Runs a single command using the runners shell
      - name: Start Client
        run: pnpm start:widget:test &

      # Runs a single command using the runners shell
      - name: Start WS
        run: pnpm start:ws:test &

      # Runs a single command using the runners shell
      - name: Wait for WS
        run: npx wait-on --timeout=30000 http://localhost:1340/v1/health-check

      - name: Cypress run
        uses: cypress-io/github-action@v2
        env:
          NODE_ENV: test
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          working-directory: apps/widget
          start: pnpm start:api
          wait-on: http://localhost:3500/v1/health-check
          record: true
          browser: chrome
          install: false
          headless: true

