name: Test @notifire/twilio
on:
  push:
    paths:
      - "providers/twilio/**"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: rm -rf build
      - run: yarn install
      - run: yarn bootstrap
      - name: Test
        working-directory: "providers/twilio"
        run: yarn run build
