# This is a basic workflow to help you get started with Actions

name: Test WEB

# Controls when the action will run. Triggers the workflow on push or pull request
on:
  workflow_dispatch:
    inputs:
      deploy:
        description: 'Should deploy'
        required: false
        default: "true"
  pull_request:
    paths:
      - 'apps/web/**'
      - 'libs/shared/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test_web:
    uses: ./.github/workflows/reusable-web-e2e.yml
    secrets: inherit
