# This is a basic workflow to help you get started with Actions

name: Test WIDGET

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
    inputs:
      deploy:
        description: 'Should deploy'
        required: false
        default: "true"
  pull_request:
    paths:
      - 'apps/widget/**'
      - 'apps/ws/**'
      - 'libs/shared/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test_widget:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 80

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup kernel for react native, increase watchers
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
      - uses: actions/setup-node@v2
        with:
          node-version: '16.13.0'
      - name: Start Redis
        uses: supercharge/redis-github-action@1.2.0

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: 4.2.8

      - name: restore lerna
        uses: actions/cache@master
        with:
          path: |
            node_modules
            **/node_modules
            /home/runner/.cache/Cypress
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      # Runs a single command using the runners shell
      - name: Install project dependencies
        run: yarn install

      # Runs a single command using the runners shell
      - name: Bootstrap
        run: yarn run bootstrap

      # Runs a single command using the runners shell
      - name: Build
        run: CI='' yarn run build:widget

      # Runs a single command using the runners shell
      - name: Start Client
        run: yarn run start:widget &

      # Runs a single command using the runners shell
      - name: Start WS
        run: yarn run start:ws &

      # Runs a single command using the runners shell
      - name: Wait for WS
        run: npx wait-on --timeout=30000 http://localhost:1340/v1/health-check

      - name: Cypress run
        uses: cypress-io/github-action@v2
        env:
          NODE_ENV: test
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          working-directory: apps/widget
          start: yarn run start:api
          wait-on: http://localhost:3500/v1/health-check
          record: true
          browser: chrome
          headless: true

