# This is a basic workflow to help you get started with Actions

name: Test WIDGET

# Controls when the action will run. Triggers the workflow on push or pull request
on:
  workflow_dispatch:
    inputs:
      deploy:
        description: 'Should deploy'
        required: false
        default: "true"
  pull_request:
    paths:
      - 'apps/widget/**'
      - 'apps/ws/**'
      - 'libs/shared/**'
      - 'packages/notification-center/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test_widget:
    uses: ./.github/workflows/reusable-widget-e2e.yml
    secrets:
      cypress_key: ${{ secrets.CYPRESS_WIDGET_KEY }}
